In [2]:
import pandas as pd
import numpy as np
import nltk
import pickle
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem.wordnet import WordNetLemmatizer
from ast import literal_eval

In [3]:
data = pd.read_csv('Hotel_Data.csv')
data.head()

,Unnamed: 0,_id,Unnamed: 2,Name,URL,Total Rating,Review_Score,New Total,Code,Rating,City_y,Amenities,Latitude,Longitude,Price,Address,City,CityLabel,cluster
0,0,628752bdd04899399ca36d45,0,Cloud Green Resort & Spa,/hotels/cloud-green-resort-spa-hotel-in-mahaba...,465 Ratings,3.9 / 5,465.0,4018,3.9,Mahabaleshwar,"['Sanitizers', 'Parking (Free)', 'Wifi (Free)'...",17582,73746,2119.0,"311, Mahabaleshwar panchgani road, near lin...",Mahabaleshwar,38,4
1,1,628752bdd04899399ca36d46,1,Forest County Resort,/hotels/forest-county-resort-hotel-in-mahabale...,225 Ratings,3.8 / 5,225.0,6018,3.8,Mahabaleshwar,"['Masks (Paid)', 'Gloves (Paid)', 'Thermal scr...",17857,73812,4650.0,"VARCHI MALUSARWADI, POST-TALDEV, HOUSE NO.82,,...",Mahabaleshwar,38,4
2,2,628752bdd04899399ca36d47,2,Regenta MPG Club,/hotels/regenta-mpg-club-hotel-in-mahabaleshwa...,391 Ratings,4.3 / 5,391.0,5018,4.3,Mahabaleshwar,"['Hair nets (for hotel staff)', 'Thermal scree...",17795,73689,6388.0,"MPG Club, 233 Old Tapola Road, Dist.Satara,",Mahabaleshwar,38,4
3,3,628752bdd04899399ca36d48,3,"Bellevue Resort, Panchgani",/hotels/bellevue-resort-panchgani-hotel-in-mah...,248 Ratings,3.9 / 5,248.0,4018,3.9,Mahabaleshwar,"['Sanitizers', 'Parking (Free)', 'Wifi (Free)'...",17,73,2392.0,"Bhilar Kaswand Road, Bhilar Hill station betwe...",Mahabaleshwar,38,4
4,4,628752bdd04899399ca36d49,4,NANDANVAN TENT AND RESORT,/hotels/nandanvan-tent-and-resort-hotel-in-mah...,27 Ratings,4.4 / 5,27.0,2017,4.4,Mahabaleshwar,['Hospital in the vicinity (Between 5 and 10 k...,17,73,2637.0,"SR NO 5/1 , NEAR BSNL OFFICE , MAHABALESHWAR T...",Mahabaleshwar,38,4

In [3]:
# columns that needs to be removed
datanames = ['_id','Review_Score','New Total','Code','City_y','Latitude','Longitude','CityLabel']
data.drop(datanames,inplace=True,axis="columns")

In [4]:
data.head()

,Unnamed: 0,Unnamed: 2,Name,URL,Total Rating,Rating,Amenities,Price,Address,City,cluster
0,0,0,Cloud Green Resort & Spa,/hotels/cloud-green-resort-spa-hotel-in-mahaba...,465 Ratings,3.9,"['Sanitizers', 'Parking (Free)', 'Wifi (Free)'...",2119.0,"311, Mahabaleshwar panchgani road, near lin...",Mahabaleshwar,4
1,1,1,Forest County Resort,/hotels/forest-county-resort-hotel-in-mahabale...,225 Ratings,3.8,"['Masks (Paid)', 'Gloves (Paid)', 'Thermal scr...",4650.0,"VARCHI MALUSARWADI, POST-TALDEV, HOUSE NO.82,,...",Mahabaleshwar,4
2,2,2,Regenta MPG Club,/hotels/regenta-mpg-club-hotel-in-mahabaleshwa...,391 Ratings,4.3,"['Hair nets (for hotel staff)', 'Thermal scree...",6388.0,"MPG Club, 233 Old Tapola Road, Dist.Satara,",Mahabaleshwar,4
3,3,3,"Bellevue Resort, Panchgani",/hotels/bellevue-resort-panchgani-hotel-in-mah...,248 Ratings,3.9,"['Sanitizers', 'Parking (Free)', 'Wifi (Free)'...",2392.0,"Bhilar Kaswand Road, Bhilar Hill station betwe...",Mahabaleshwar,4
4,4,4,NANDANVAN TENT AND RESORT,/hotels/nandanvan-tent-and-resort-hotel-in-mah...,27 Ratings,4.4,['Hospital in the vicinity (Between 5 and 10 k...,2637.0,"SR NO 5/1 , NEAR BSNL OFFICE , MAHABALESHWAR T...",Mahabaleshwar,4

In [10]:
n=['Unnamed: 2']
data.drop(n,inplace=True,axis="columns")

In [11]:
data.head()

,Name,URL,Total Rating,Rating,Amenities,Price,Address,City,cluster
0,Cloud Green Resort & Spa,/hotels/cloud-green-resort-spa-hotel-in-mahaba...,465 Ratings,3.9,"['Sanitizers', 'Parking (Free)', 'Wifi (Free)'...",2119.0,"311, Mahabaleshwar panchgani road, near lin...",Mahabaleshwar,4
1,Forest County Resort,/hotels/forest-county-resort-hotel-in-mahabale...,225 Ratings,3.8,"['Masks (Paid)', 'Gloves (Paid)', 'Thermal scr...",4650.0,"VARCHI MALUSARWADI, POST-TALDEV, HOUSE NO.82,,...",Mahabaleshwar,4
2,Regenta MPG Club,/hotels/regenta-mpg-club-hotel-in-mahabaleshwa...,391 Ratings,4.3,"['Hair nets (for hotel staff)', 'Thermal scree...",6388.0,"MPG Club, 233 Old Tapola Road, Dist.Satara,",Mahabaleshwar,4
3,"Bellevue Resort, Panchgani",/hotels/bellevue-resort-panchgani-hotel-in-mah...,248 Ratings,3.9,"['Sanitizers', 'Parking (Free)', 'Wifi (Free)'...",2392.0,"Bhilar Kaswand Road, Bhilar Hill station betwe...",Mahabaleshwar,4
4,NANDANVAN TENT AND RESORT,/hotels/nandanvan-tent-and-resort-hotel-in-mah...,27 Ratings,4.4,['Hospital in the vicinity (Between 5 and 10 k...,2637.0,"SR NO 5/1 , NEAR BSNL OFFICE , MAHABALESHWAR T...",Mahabaleshwar,4

In [14]:
data.rename(columns={'Name':'hotel_name'},inplace=True)

In [15]:
data.to_csv('modified_data.csv',index=False)

In [18]:
info = pd.read_csv('Hotel_Info.csv')
info.head()

,Unnamed: 0,Code,City,Amenities,Latitude,Longitude,Price,Address
0,0,1.001080e+18,Coorg,"['Kitchen/Kitchenette', 'Housekeeping', 'Parki...",12.4503,75.7124,5400,"Kootuhole,Galibeedu Road, Madikeri"
1,1,1.001340e+18,udaipur,"['Masks', 'Sanitizers (Free)', 'Sanitizers ins...",24.6263,73.7111,2158,"sohan sadan,near PNB bank, bhuwana by pass cho..."
2,2,1.001850e+18,Lake,"['Parking (Free)', 'Wifi (Free)', 'Elevator/ L...",28.8982,-81.9110,7001,850 South US Hwy 27/441
3,3,1.004070e+18,Mysore,"['Masks (Paid)', 'Disinfectant wipes (Paid)', ...",12.3046,76.6664,1004,"15/B, HOTEL THE GRAND VANAM, LOKARANJANMAHAL\r..."
4,4,1.004500e+18,Mahabaleshwar,"['Masks', 'Gloves (Paid)', 'Thermal screening ...",17.9235,73.7986,1812,"Pan Hill Hotel, Opposite Bus Stand, Panchgani ..."

In [19]:
infonames = ['Unnamed: 0','Code','Price']
info.drop(infonames,inplace=True,axis='columns')

In [20]:
info.head()

,City,Amenities,Latitude,Longitude,Address
0,Coorg,"['Kitchen/Kitchenette', 'Housekeeping', 'Parki...",12.4503,75.7124,"Kootuhole,Galibeedu Road, Madikeri"
1,udaipur,"['Masks', 'Sanitizers (Free)', 'Sanitizers ins...",24.6263,73.7111,"sohan sadan,near PNB bank, bhuwana by pass cho..."
2,Lake,"['Parking (Free)', 'Wifi (Free)', 'Elevator/ L...",28.8982,-81.9110,850 South US Hwy 27/441
3,Mysore,"['Masks (Paid)', 'Disinfectant wipes (Paid)', ...",12.3046,76.6664,"15/B, HOTEL THE GRAND VANAM, LOKARANJANMAHAL\r..."
4,Mahabaleshwar,"['Masks', 'Gloves (Paid)', 'Thermal screening ...",17.9235,73.7986,"Pan Hill Hotel, Opposite Bus Stand, Panchgani ..."

In [21]:
info.to_csv('modified_info.csv',index=False)

In [22]:
landmark = pd.read_csv('Hotel_Landmarks.csv')
landmark.head()

,Unnamed: 0.1,Unnamed: 0,Code,City,Landmarks,Distance,Latitude,Longitud,Type
0,0,0,1001082775062077907,Coorg,Omkareshwara temple,4.6,12.420561,75.741264,Religious Place
1,1,1,1001082775062077907,Coorg,Madikeri Fort near Bhagamandala,5.8,12.386219,75.529854,NaN
2,2,2,1001082775062077907,Coorg,Gaddige,4.4,12.433463,75.739693,NaN
3,3,3,1001082775062077907,Coorg,Cauvery Mahal Theater,4.7,12.425710,75.736010,Recreation
4,4,4,1001082775062077907,Coorg,KSRTC Bus Station,4.9,12.423185,75.737872,NaN

In [23]:
landmarknames = ['Unnamed: 0.1','Unnamed: 0','Type']
landmark.drop(landmarknames,inplace=True,axis="columns")

In [24]:
landmark.head()

,Code,City,Landmarks,Distance,Latitude,Longitud
0,1001082775062077907,Coorg,Omkareshwara temple,4.6,12.420561,75.741264
1,1001082775062077907,Coorg,Madikeri Fort near Bhagamandala,5.8,12.386219,75.529854
2,1001082775062077907,Coorg,Gaddige,4.4,12.433463,75.739693
3,1001082775062077907,Coorg,Cauvery Mahal Theater,4.7,12.425710,75.736010
4,1001082775062077907,Coorg,KSRTC Bus Station,4.9,12.423185,75.737872

In [25]:
landmark.to_csv('modified_landmark.csv',index=False)

-> ALL THE REQUIRED CSV FILES HAVE BEEN MODIFIED 
-> NOW WE NEED TO MERGE
-> REVIEW FILE IS WASTE AND NO USABLE FOR OUR PROJECT AS WE CANN'T MERGE IT ANYOTHER CSV FILE

In [147]:
m_data = pd.read_csv('modified_data.csv')
m_info = pd.read_csv('modified_info.csv')
m_landmark = pd.read_csv('modified_landmark.csv')

In [28]:
# merging data and info on Amenities
m_merged = m_data.merge(m_info,on="Amenities",how="inner")
m_merged.head()

,hotel_name,URL,Total Rating,Rating,Amenities,Price,Address_x,City_x,cluster,City_y,Latitude,Longitude,Address_y
0,Cloud Green Resort & Spa,/hotels/cloud-green-resort-spa-hotel-in-mahaba...,465 Ratings,3.9,"['Sanitizers', 'Parking (Free)', 'Wifi (Free)'...",2119.0,"311, Mahabaleshwar panchgani road, near lin...",Mahabaleshwar,4,Mahabaleshwar,17.926366,73.693817,"311, Mahabaleshwar panchgani road, near lin..."
1,Forest County Resort,/hotels/forest-county-resort-hotel-in-mahabale...,225 Ratings,3.8,"['Masks (Paid)', 'Gloves (Paid)', 'Thermal scr...",4650.0,"VARCHI MALUSARWADI, POST-TALDEV, HOUSE NO.82,,...",Mahabaleshwar,4,Mahabaleshwar,17.881969,73.671178,"VARCHI MALUSARWADI, POST-TALDEV, HOUSE NO.82,,..."
2,Regenta MPG Club,/hotels/regenta-mpg-club-hotel-in-mahabaleshwa...,391 Ratings,4.3,"['Hair nets (for hotel staff)', 'Thermal scree...",6388.0,"MPG Club, 233 Old Tapola Road, Dist.Satara,",Mahabaleshwar,4,Mahabaleshwar,17.917108,73.661507,"MPG Club, 233 Old Tapola Road, Dist.Satara,"
3,"Bellevue Resort, Panchgani",/hotels/bellevue-resort-panchgani-hotel-in-mah...,248 Ratings,3.9,"['Sanitizers', 'Parking (Free)', 'Wifi (Free)'...",2392.0,"Bhilar Kaswand Road, Bhilar Hill station betwe...",Mahabaleshwar,4,Mahabaleshwar,17.906700,73.770800,"Bhilar Kaswand Road, Bhilar Hill station betwe..."
4,NANDANVAN TENT AND RESORT,/hotels/nandanvan-tent-and-resort-hotel-in-mah...,27 Ratings,4.4,['Hospital in the vicinity (Between 5 and 10 k...,2637.0,"SR NO 5/1 , NEAR BSNL OFFICE , MAHABALESHWAR T...",Mahabaleshwar,4,Mahabaleshwar,17.769300,73.738200,"SR NO 5/1 , NEAR BSNL OFFICE , MAHABALESHWAR T..."

In [29]:
m_merged_names = ['Address_x','City_x']
m_merged.drop(m_merged_names,inplace=True,axis="columns")
m_merged.head()

,hotel_name,URL,Total Rating,Rating,Amenities,Price,cluster,City_y,Latitude,Longitude,Address_y
0,Cloud Green Resort & Spa,/hotels/cloud-green-resort-spa-hotel-in-mahaba...,465 Ratings,3.9,"['Sanitizers', 'Parking (Free)', 'Wifi (Free)'...",2119.0,4,Mahabaleshwar,17.926366,73.693817,"311, Mahabaleshwar panchgani road, near lin..."
1,Forest County Resort,/hotels/forest-county-resort-hotel-in-mahabale...,225 Ratings,3.8,"['Masks (Paid)', 'Gloves (Paid)', 'Thermal scr...",4650.0,4,Mahabaleshwar,17.881969,73.671178,"VARCHI MALUSARWADI, POST-TALDEV, HOUSE NO.82,,..."
2,Regenta MPG Club,/hotels/regenta-mpg-club-hotel-in-mahabaleshwa...,391 Ratings,4.3,"['Hair nets (for hotel staff)', 'Thermal scree...",6388.0,4,Mahabaleshwar,17.917108,73.661507,"MPG Club, 233 Old Tapola Road, Dist.Satara,"
3,"Bellevue Resort, Panchgani",/hotels/bellevue-resort-panchgani-hotel-in-mah...,248 Ratings,3.9,"['Sanitizers', 'Parking (Free)', 'Wifi (Free)'...",2392.0,4,Mahabaleshwar,17.906700,73.770800,"Bhilar Kaswand Road, Bhilar Hill station betwe..."
4,NANDANVAN TENT AND RESORT,/hotels/nandanvan-tent-and-resort-hotel-in-mah...,27 Ratings,4.4,['Hospital in the vicinity (Between 5 and 10 k...,2637.0,4,Mahabaleshwar,17.769300,73.738200,"SR NO 5/1 , NEAR BSNL OFFICE , MAHABALESHWAR T..."

In [30]:
m_merged.rename(columns={"City_y":"City","Address_y":"Address"},inplace=True)
m_merged.head()

,hotel_name,URL,Total Rating,Rating,Amenities,Price,cluster,City,Latitude,Longitude,Address
0,Cloud Green Resort & Spa,/hotels/cloud-green-resort-spa-hotel-in-mahaba...,465 Ratings,3.9,"['Sanitizers', 'Parking (Free)', 'Wifi (Free)'...",2119.0,4,Mahabaleshwar,17.926366,73.693817,"311, Mahabaleshwar panchgani road, near lin..."
1,Forest County Resort,/hotels/forest-county-resort-hotel-in-mahabale...,225 Ratings,3.8,"['Masks (Paid)', 'Gloves (Paid)', 'Thermal scr...",4650.0,4,Mahabaleshwar,17.881969,73.671178,"VARCHI MALUSARWADI, POST-TALDEV, HOUSE NO.82,,..."
2,Regenta MPG Club,/hotels/regenta-mpg-club-hotel-in-mahabaleshwa...,391 Ratings,4.3,"['Hair nets (for hotel staff)', 'Thermal scree...",6388.0,4,Mahabaleshwar,17.917108,73.661507,"MPG Club, 233 Old Tapola Road, Dist.Satara,"
3,"Bellevue Resort, Panchgani",/hotels/bellevue-resort-panchgani-hotel-in-mah...,248 Ratings,3.9,"['Sanitizers', 'Parking (Free)', 'Wifi (Free)'...",2392.0,4,Mahabaleshwar,17.906700,73.770800,"Bhilar Kaswand Road, Bhilar Hill station betwe..."
4,NANDANVAN TENT AND RESORT,/hotels/nandanvan-tent-and-resort-hotel-in-mah...,27 Ratings,4.4,['Hospital in the vicinity (Between 5 and 10 k...,2637.0,4,Mahabaleshwar,17.769300,73.738200,"SR NO 5/1 , NEAR BSNL OFFICE , MAHABALESHWAR T..."

In [31]:
m_merged.to_csv("modified_merged.csv",index=False)

need to create a new csv file containing all the amenities of each city and change the amenities column of all the modified files

In [13]:
amenity_df = pd.read_csv("modified_data.csv")

In [14]:
amenity_df.head()

,hotel_name,URL,Total Rating,Rating,Amenities,Price,Address,City,cluster
0,Cloud Green Resort & Spa,/hotels/cloud-green-resort-spa-hotel-in-mahaba...,465 Ratings,3.9,"['Sanitizers', 'Parking (Free)', 'Wifi (Free)'...",2119.0,"311, Mahabaleshwar panchgani road, near lin...",Mahabaleshwar,4
1,Forest County Resort,/hotels/forest-county-resort-hotel-in-mahabale...,225 Ratings,3.8,"['Masks (Paid)', 'Gloves (Paid)', 'Thermal scr...",4650.0,"VARCHI MALUSARWADI, POST-TALDEV, HOUSE NO.82,,...",Mahabaleshwar,4
2,Regenta MPG Club,/hotels/regenta-mpg-club-hotel-in-mahabaleshwa...,391 Ratings,4.3,"['Hair nets (for hotel staff)', 'Thermal scree...",6388.0,"MPG Club, 233 Old Tapola Road, Dist.Satara,",Mahabaleshwar,4
3,"Bellevue Resort, Panchgani",/hotels/bellevue-resort-panchgani-hotel-in-mah...,248 Ratings,3.9,"['Sanitizers', 'Parking (Free)', 'Wifi (Free)'...",2392.0,"Bhilar Kaswand Road, Bhilar Hill station betwe...",Mahabaleshwar,4
4,NANDANVAN TENT AND RESORT,/hotels/nandanvan-tent-and-resort-hotel-in-mah...,27 Ratings,4.4,['Hospital in the vicinity (Between 5 and 10 k...,2637.0,"SR NO 5/1 , NEAR BSNL OFFICE , MAHABALESHWAR T...",Mahabaleshwar,4

In [15]:
names = ['URL','Total Rating','Rating','Price','Address','cluster']
amenity_df.drop(names,inplace=True,axis="columns")

In [16]:
amenity_df.head()

,hotel_name,Amenities,City
0,Cloud Green Resort & Spa,"['Sanitizers', 'Parking (Free)', 'Wifi (Free)'...",Mahabaleshwar
1,Forest County Resort,"['Masks (Paid)', 'Gloves (Paid)', 'Thermal scr...",Mahabaleshwar
2,Regenta MPG Club,"['Hair nets (for hotel staff)', 'Thermal scree...",Mahabaleshwar
3,"Bellevue Resort, Panchgani","['Sanitizers', 'Parking (Free)', 'Wifi (Free)'...",Mahabaleshwar
4,NANDANVAN TENT AND RESORT,['Hospital in the vicinity (Between 5 and 10 k...,Mahabaleshwar

In [20]:
amenity = []+list(amenity_df['Amenities'])

# print(type(amenity)) # output is list

need to remove data from the modified_data csv file which has no rating

In [45]:
merge = pd.read_csv('modified_merged.csv')
merge.head()

,hotel_name,URL,Total Rating,Rating,Amenities,Price,cluster,City,Latitude,Longitude,Address
0,Cloud Green Resort & Spa,/hotels/cloud-green-resort-spa-hotel-in-mahaba...,465 Ratings,3.9,"['Sanitizers', 'Parking (Free)', 'Wifi (Free)'...",2119.0,4,Mahabaleshwar,17.926366,73.693817,"311, Mahabaleshwar panchgani road, near lin..."
1,Forest County Resort,/hotels/forest-county-resort-hotel-in-mahabale...,225 Ratings,3.8,"['Masks (Paid)', 'Gloves (Paid)', 'Thermal scr...",4650.0,4,Mahabaleshwar,17.881969,73.671178,"VARCHI MALUSARWADI, POST-TALDEV, HOUSE NO.82,,..."
2,Regenta MPG Club,/hotels/regenta-mpg-club-hotel-in-mahabaleshwa...,391 Ratings,4.3,"['Hair nets (for hotel staff)', 'Thermal scree...",6388.0,4,Mahabaleshwar,17.917108,73.661507,"MPG Club, 233 Old Tapola Road, Dist.Satara,"
3,"Bellevue Resort, Panchgani",/hotels/bellevue-resort-panchgani-hotel-in-mah...,248 Ratings,3.9,"['Sanitizers', 'Parking (Free)', 'Wifi (Free)'...",2392.0,4,Mahabaleshwar,17.906700,73.770800,"Bhilar Kaswand Road, Bhilar Hill station betwe..."
4,NANDANVAN TENT AND RESORT,/hotels/nandanvan-tent-and-resort-hotel-in-mah...,27 Ratings,4.4,['Hospital in the vicinity (Between 5 and 10 k...,2637.0,4,Mahabaleshwar,17.769300,73.738200,"SR NO 5/1 , NEAR BSNL OFFICE , MAHABALESHWAR T..."

In [46]:
# Remove rows where 'rating' has NaN or empty values
cleaned_data = merge.dropna(subset=['Rating'])

In [47]:
cleaned_data.head()

,hotel_name,URL,Total Rating,Rating,Amenities,Price,cluster,City,Latitude,Longitude,Address
0,Cloud Green Resort & Spa,/hotels/cloud-green-resort-spa-hotel-in-mahaba...,465 Ratings,3.9,"['Sanitizers', 'Parking (Free)', 'Wifi (Free)'...",2119.0,4,Mahabaleshwar,17.926366,73.693817,"311, Mahabaleshwar panchgani road, near lin..."
1,Forest County Resort,/hotels/forest-county-resort-hotel-in-mahabale...,225 Ratings,3.8,"['Masks (Paid)', 'Gloves (Paid)', 'Thermal scr...",4650.0,4,Mahabaleshwar,17.881969,73.671178,"VARCHI MALUSARWADI, POST-TALDEV, HOUSE NO.82,,..."
2,Regenta MPG Club,/hotels/regenta-mpg-club-hotel-in-mahabaleshwa...,391 Ratings,4.3,"['Hair nets (for hotel staff)', 'Thermal scree...",6388.0,4,Mahabaleshwar,17.917108,73.661507,"MPG Club, 233 Old Tapola Road, Dist.Satara,"
3,"Bellevue Resort, Panchgani",/hotels/bellevue-resort-panchgani-hotel-in-mah...,248 Ratings,3.9,"['Sanitizers', 'Parking (Free)', 'Wifi (Free)'...",2392.0,4,Mahabaleshwar,17.906700,73.770800,"Bhilar Kaswand Road, Bhilar Hill station betwe..."
4,NANDANVAN TENT AND RESORT,/hotels/nandanvan-tent-and-resort-hotel-in-mah...,27 Ratings,4.4,['Hospital in the vicinity (Between 5 and 10 k...,2637.0,4,Mahabaleshwar,17.769300,73.738200,"SR NO 5/1 , NEAR BSNL OFFICE , MAHABALESHWAR T..."

#cleaned_data.to_csv('cleaned_data.csv',index=False)

now there are around 8.6k instances instead of 11k instances 
now we need to remove the data which has no amenities

In [48]:
cleaned_data.head()

,hotel_name,URL,Total Rating,Rating,Amenities,Price,cluster,City,Latitude,Longitude,Address
0,Cloud Green Resort & Spa,/hotels/cloud-green-resort-spa-hotel-in-mahaba...,465 Ratings,3.9,"['Sanitizers', 'Parking (Free)', 'Wifi (Free)'...",2119.0,4,Mahabaleshwar,17.926366,73.693817,"311, Mahabaleshwar panchgani road, near lin..."
1,Forest County Resort,/hotels/forest-county-resort-hotel-in-mahabale...,225 Ratings,3.8,"['Masks (Paid)', 'Gloves (Paid)', 'Thermal scr...",4650.0,4,Mahabaleshwar,17.881969,73.671178,"VARCHI MALUSARWADI, POST-TALDEV, HOUSE NO.82,,..."
2,Regenta MPG Club,/hotels/regenta-mpg-club-hotel-in-mahabaleshwa...,391 Ratings,4.3,"['Hair nets (for hotel staff)', 'Thermal scree...",6388.0,4,Mahabaleshwar,17.917108,73.661507,"MPG Club, 233 Old Tapola Road, Dist.Satara,"
3,"Bellevue Resort, Panchgani",/hotels/bellevue-resort-panchgani-hotel-in-mah...,248 Ratings,3.9,"['Sanitizers', 'Parking (Free)', 'Wifi (Free)'...",2392.0,4,Mahabaleshwar,17.906700,73.770800,"Bhilar Kaswand Road, Bhilar Hill station betwe..."
4,NANDANVAN TENT AND RESORT,/hotels/nandanvan-tent-and-resort-hotel-in-mah...,27 Ratings,4.4,['Hospital in the vicinity (Between 5 and 10 k...,2637.0,4,Mahabaleshwar,17.769300,73.738200,"SR NO 5/1 , NEAR BSNL OFFICE , MAHABALESHWAR T..."

In [49]:
cleaned_data['Amenities'] = cleaned_data['Amenities'].apply(literal_eval)

/var/folders/82/xgc3z5fn3wv_9_j7dffh1_sw0000gn/T/ipykernel_29807/2766535528.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleaned_data['Amenities'] = cleaned_data['Amenities'].apply(literal_eval)

In [50]:
cleaned_data = cleaned_data[cleaned_data['Amenities'].apply(lambda x: len(x)>0)]

In [51]:
cleaned_data.to_csv('cleaned_data.csv',index=False)

now there are around 8k instances

we need to create a new dataset which contains cities and their corresponding amenities

In [52]:
data = pd.read_csv('cleaned_data.csv')
data.head()

,hotel_name,URL,Total Rating,Rating,Amenities,Price,cluster,City,Latitude,Longitude,Address
0,Cloud Green Resort & Spa,/hotels/cloud-green-resort-spa-hotel-in-mahaba...,465 Ratings,3.9,"['Sanitizers', 'Parking (Free)', 'Wifi (Free)'...",2119.0,4,Mahabaleshwar,17.926366,73.693817,"311, Mahabaleshwar panchgani road, near lin..."
1,Forest County Resort,/hotels/forest-county-resort-hotel-in-mahabale...,225 Ratings,3.8,"['Masks (Paid)', 'Gloves (Paid)', 'Thermal scr...",4650.0,4,Mahabaleshwar,17.881969,73.671178,"VARCHI MALUSARWADI, POST-TALDEV, HOUSE NO.82,,..."
2,Regenta MPG Club,/hotels/regenta-mpg-club-hotel-in-mahabaleshwa...,391 Ratings,4.3,"['Hair nets (for hotel staff)', 'Thermal scree...",6388.0,4,Mahabaleshwar,17.917108,73.661507,"MPG Club, 233 Old Tapola Road, Dist.Satara,"
3,"Bellevue Resort, Panchgani",/hotels/bellevue-resort-panchgani-hotel-in-mah...,248 Ratings,3.9,"['Sanitizers', 'Parking (Free)', 'Wifi (Free)'...",2392.0,4,Mahabaleshwar,17.906700,73.770800,"Bhilar Kaswand Road, Bhilar Hill station betwe..."
4,NANDANVAN TENT AND RESORT,/hotels/nandanvan-tent-and-resort-hotel-in-mah...,27 Ratings,4.4,['Hospital in the vicinity (Between 5 and 10 k...,2637.0,4,Mahabaleshwar,17.769300,73.738200,"SR NO 5/1 , NEAR BSNL OFFICE , MAHABALESHWAR T..."

In [142]:
# list = ['hotel_name','URL','Total Rating','Rating','Price','cluster','Latitude','Longitude','Address']
# data.drop(list,inplace=True,axis="columns")

In [143]:
data.head()

                                           Amenities           City
0  ['Sanitizers', 'Parking (Free)', 'Wifi (Free)'...  Mahabaleshwar
1  ['Masks (Paid)', 'Gloves (Paid)', 'Thermal scr...  Mahabaleshwar
2  ['Hair nets (for hotel staff)', 'Thermal scree...  Mahabaleshwar
3  ['Sanitizers', 'Parking (Free)', 'Wifi (Free)'...  Mahabaleshwar
4  ['Hospital in the vicinity (Between 5 and 10 k...  Mahabaleshwar

In [59]:
unique_cities = data['City'].unique()

In [61]:
print(unique_cities)
print(type(unique_cities))

['Mahabaleshwar' 'Mahabalipuram' 'Manali' 'Mysore' 'Mussoorie' 'Mathura'
 'Agra' 'udaipur' 'Ranchi' 'Mcleodganj' 'Nainital' 'Munnar' 'Mumbai'
 'Coorg' 'Mukteshwar' 'Park' 'Ooty' 'Pushkar' 'Pondicherry' 'Orchha'
 'Rishikesh' 'Ranikhet' 'Shimla' 'Sonamarg' 'Shirdi' 'Srinagar' 'Spiti'
 'Shimoga' 'Tirupati' 'Tawang' 'Varanasi' 'Varkala' 'Chopta' 'Coonoor'
 'Dalhousie' 'Madikeri' 'Gaya' 'Dhanaulti' 'Darjeeling' 'Gangtok'
 'Gokarna' 'Deoghar' 'Hazaribagh' 'Gulmarg' 'Jabalpur' 'Visakhapatnam'
 'Hampi' 'Kanatal' 'Joshimath' 'Auli' 'Kasol' 'Jodhpur' 'Kanyakumari'
 'Jaisalmer' 'Kausani' 'Khajjiar' 'Khajuraho' 'Kodaikanal' 'Cherrapunji'
 'Madurai' 'Lake' 'Lonavala' 'Wayanad' 'Ziro' 'Abu' 'Ajmer' 'Alleppey'
 'Binsar' 'Almora' 'Bankura' 'Chandigarh']
<class 'numpy.ndarray'>

In [65]:
unique_cities_list = unique_cities.tolist()
print(unique_cities_list)

['Mahabaleshwar', 'Mahabalipuram', 'Manali', 'Mysore', 'Mussoorie', 'Mathura', 'Agra', 'udaipur', 'Ranchi', 'Mcleodganj', 'Nainital', 'Munnar', 'Mumbai', 'Coorg', 'Mukteshwar', 'Park', 'Ooty', 'Pushkar', 'Pondicherry', 'Orchha', 'Rishikesh', 'Ranikhet', 'Shimla', 'Sonamarg', 'Shirdi', 'Srinagar', 'Spiti', 'Shimoga', 'Tirupati', 'Tawang', 'Varanasi', 'Varkala', 'Chopta', 'Coonoor', 'Dalhousie', 'Madikeri', 'Gaya', 'Dhanaulti', 'Darjeeling', 'Gangtok', 'Gokarna', 'Deoghar', 'Hazaribagh', 'Gulmarg', 'Jabalpur', 'Visakhapatnam', 'Hampi', 'Kanatal', 'Joshimath', 'Auli', 'Kasol', 'Jodhpur', 'Kanyakumari', 'Jaisalmer', 'Kausani', 'Khajjiar', 'Khajuraho', 'Kodaikanal', 'Cherrapunji', 'Madurai', 'Lake', 'Lonavala', 'Wayanad', 'Ziro', 'Abu', 'Ajmer', 'Alleppey', 'Binsar', 'Almora', 'Bankura', 'Chandigarh']
<class 'list'>

In [105]:
print(type(data["Amenities"]))
amenities = data["Amenities"]
print(len(amenities))

<class 'pandas.core.series.Series'>
8070

In [74]:
amenities_list = data["Amenities"].to_list()
print(amenities_list[0])

['Sanitizers', 'Parking (Free)', 'Wifi (Free)', 'Air Conditioning', 'Room service (Limited duration)', 'Power backup', 'Intercom', 'Telephone', 'Housekeeping', 'Public restrooms', 'Laundry (Paid)', 'Newspaper (English)', 'Bathroom (Attached)', 'Swimming Pool (Common Pool, Kids Pool)', "Children's play area", 'Restaurant', 'Dining Area', 'Barbeque', 'Kids meals', 'CCTV', 'Fire extinguishers', 'Security', 'Luggage storage', 'Mail services', 'Luggage assistance', 'Electrical Sockets', 'Doctor on call', 'Ticket/ Tour Assistance', 'Bellboy service', 'Wake-up Call / Service', 'Facial treatments', 'Spa (Paid)', 'Massage (Couple Massage, Foot massage)', 'Steam and Sauna (Paid)', 'Bonfire (On Request)', 'Vehicle Rentals', 'Indoor games', 'Lawn', 'Reception', 'Seating Area', 'Conference room', 'Printer']

In [ ]:
# hotel_amenities = data[data['hotel_name'] == hotel]['Amenities']
# raw_amenities = hotel_amenities.iloc[0]

# actual_list = literal_eval(raw_amenities)

In [111]:
print(type(data["Amenities"]))
amenities = data["Amenities"]
raw_amen = data['Amenities'].iloc[len(amenities)-1]
actual_raw_amen = literal_eval(raw_amen)
print(actual_raw_amen)

<class 'pandas.core.series.Series'>
['Sanitizers', 'Face shields (for hotel staff)', 'Sanitizers installed', 'Disinfection', 'Hospital in the vicinity', 'Room service (Limited duration)', 'Power backup', 'Intercom', 'Telephone', 'Housekeeping', 'Bathroom (Attached)', 'CCTV', 'Fire extinguishers', 'Safety and Security', 'Security', 'TV', 'Luggage storage', 'Multilingual Staff', 'Electrical Sockets', 'Caretaker', 'Wake-up Call / Service', 'Reception', 'Seating Area']

in the above snippet the function iloc[] selects the row based on the value inside the square bracket

In [90]:
# print(len(data["Amenities"]))

8070

the following function is used to create a dictionary that contains all the amenities a city has and will be used for sort_amenity

In [130]:
def city_amenities(cities):
    amen_city = {} # this is a dictionary which contains (city) : ( corresponding amenities )
    for j in cities:
        l = [] # this is a 2d array
        # j = city
        Amenity = data[data['City']==j]['Amenities']
        for i in range(len(data["Amenities"])):
            raw_amen = data[data['City']==j]["Amenities"].iloc[i]
            actual_raw_amen = literal_eval(raw_amen)
            l.extend(actual_raw_amen)
        amen_city[j] = l
        # raw_amen = data[data['City']==j]["Amenities"].iloc[0]
        # actual_raw_amen = literal_eval(raw_amen)
        # l.extend(actual_raw_amen)
        # amen_city[j]=l
    return amen_city

In [134]:
# amen = city_amenities(unique_cities)
print(unique_cities)

['Mahabaleshwar' 'Mahabalipuram' 'Manali' 'Mysore' 'Mussoorie' 'Mathura'
 'Agra' 'udaipur' 'Ranchi' 'Mcleodganj' 'Nainital' 'Munnar' 'Mumbai'
 'Coorg' 'Mukteshwar' 'Park' 'Ooty' 'Pushkar' 'Pondicherry' 'Orchha'
 'Rishikesh' 'Ranikhet' 'Shimla' 'Sonamarg' 'Shirdi' 'Srinagar' 'Spiti'
 'Shimoga' 'Tirupati' 'Tawang' 'Varanasi' 'Varkala' 'Chopta' 'Coonoor'
 'Dalhousie' 'Madikeri' 'Gaya' 'Dhanaulti' 'Darjeeling' 'Gangtok'
 'Gokarna' 'Deoghar' 'Hazaribagh' 'Gulmarg' 'Jabalpur' 'Visakhapatnam'
 'Hampi' 'Kanatal' 'Joshimath' 'Auli' 'Kasol' 'Jodhpur' 'Kanyakumari'
 'Jaisalmer' 'Kausani' 'Khajjiar' 'Khajuraho' 'Kodaikanal' 'Cherrapunji'
 'Madurai' 'Lake' 'Lonavala' 'Wayanad' 'Ziro' 'Abu' 'Ajmer' 'Alleppey'
 'Binsar' 'Almora' 'Bankura' 'Chandigarh']

In [135]:
d1 = pd.read_csv('cleaned_data.csv')
d1.head()

,hotel_name,URL,Total Rating,Rating,Amenities,Price,cluster,City,Latitude,Longitude,Address
0,Cloud Green Resort & Spa,/hotels/cloud-green-resort-spa-hotel-in-mahaba...,465 Ratings,3.9,"['Sanitizers', 'Parking (Free)', 'Wifi (Free)'...",2119.0,4,Mahabaleshwar,17.926366,73.693817,"311, Mahabaleshwar panchgani road, near lin..."
1,Forest County Resort,/hotels/forest-county-resort-hotel-in-mahabale...,225 Ratings,3.8,"['Masks (Paid)', 'Gloves (Paid)', 'Thermal scr...",4650.0,4,Mahabaleshwar,17.881969,73.671178,"VARCHI MALUSARWADI, POST-TALDEV, HOUSE NO.82,,..."
2,Regenta MPG Club,/hotels/regenta-mpg-club-hotel-in-mahabaleshwa...,391 Ratings,4.3,"['Hair nets (for hotel staff)', 'Thermal scree...",6388.0,4,Mahabaleshwar,17.917108,73.661507,"MPG Club, 233 Old Tapola Road, Dist.Satara,"
3,"Bellevue Resort, Panchgani",/hotels/bellevue-resort-panchgani-hotel-in-mah...,248 Ratings,3.9,"['Sanitizers', 'Parking (Free)', 'Wifi (Free)'...",2392.0,4,Mahabaleshwar,17.906700,73.770800,"Bhilar Kaswand Road, Bhilar Hill station betwe..."
4,NANDANVAN TENT AND RESORT,/hotels/nandanvan-tent-and-resort-hotel-in-mah...,27 Ratings,4.4,['Hospital in the vicinity (Between 5 and 10 k...,2637.0,4,Mahabaleshwar,17.769300,73.738200,"SR NO 5/1 , NEAR BSNL OFFICE , MAHABALESHWAR T..."

In [136]:
list = ['hotel_name','URL','Total Rating','Rating','Price','cluster','Latitude','Longitude','Address']
d1.drop(list,inplace=True,axis="columns")

In [137]:
d1.head()

                                           Amenities           City
0  ['Sanitizers', 'Parking (Free)', 'Wifi (Free)'...  Mahabaleshwar
1  ['Masks (Paid)', 'Gloves (Paid)', 'Thermal scr...  Mahabaleshwar
2  ['Hair nets (for hotel staff)', 'Thermal scree...  Mahabaleshwar
3  ['Sanitizers', 'Parking (Free)', 'Wifi (Free)'...  Mahabaleshwar
4  ['Hospital in the vicinity (Between 5 and 10 k...  Mahabaleshwar

In [138]:
# Convert string representations of lists into actual lists
d1['Amenities'] = d1['Amenities'].apply(literal_eval)

In [139]:
# Group by city and concatenate the amenities into unique lists
def concat_unique(amenity_lists):
    unique_amenities = set()
    for amenity_list in amenity_lists:
        unique_amenities.update(amenity_list)
    return list(unique_amenities)

# Group by city and apply the custom aggregation function
grouped_data = d1.groupby('City')['Amenities'].agg(concat_unique).reset_index()

# Rename the column for clarity
grouped_data.rename(columns={'Amenities': 'Combined_Amenities'}, inplace=True)

TypeError: 'list' object is not callable

you will get an error saying that list is not callable coz i have used list as a variable and i am not able to fix it

In [148]:
m_data.head()

,hotel_name,URL,Total Rating,Rating,Amenities,Price,Address,City,cluster
0,Cloud Green Resort & Spa,/hotels/cloud-green-resort-spa-hotel-in-mahaba...,465 Ratings,3.9,"['Sanitizers', 'Parking (Free)', 'Wifi (Free)'...",2119.0,"311, Mahabaleshwar panchgani road, near lin...",Mahabaleshwar,4
1,Forest County Resort,/hotels/forest-county-resort-hotel-in-mahabale...,225 Ratings,3.8,"['Masks (Paid)', 'Gloves (Paid)', 'Thermal scr...",4650.0,"VARCHI MALUSARWADI, POST-TALDEV, HOUSE NO.82,,...",Mahabaleshwar,4
2,Regenta MPG Club,/hotels/regenta-mpg-club-hotel-in-mahabaleshwa...,391 Ratings,4.3,"['Hair nets (for hotel staff)', 'Thermal scree...",6388.0,"MPG Club, 233 Old Tapola Road, Dist.Satara,",Mahabaleshwar,4
3,"Bellevue Resort, Panchgani",/hotels/bellevue-resort-panchgani-hotel-in-mah...,248 Ratings,3.9,"['Sanitizers', 'Parking (Free)', 'Wifi (Free)'...",2392.0,"Bhilar Kaswand Road, Bhilar Hill station betwe...",Mahabaleshwar,4
4,NANDANVAN TENT AND RESORT,/hotels/nandanvan-tent-and-resort-hotel-in-mah...,27 Ratings,4.4,['Hospital in the vicinity (Between 5 and 10 k...,2637.0,"SR NO 5/1 , NEAR BSNL OFFICE , MAHABALESHWAR T...",Mahabaleshwar,4